# Generated by Django 5.2.17 on 2026-09-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('B', 'Bajo'), ('M', 'Medio'), ('A', 'Alto'), ('E', 'Extremo')], default='B', max_length=1, verbose_name='Nivel de alerta')),
                ('emision', models.DateField()),
                ('descripcion', models.CharField(default='Sin descripción', max_length=100)),
                ('expiracion', models.DateField()),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='destinos.destino')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['emision'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('O', 'Obligatoria'), ('R', 'Recomendada')], default='R', max_length=1, verbose_name='Tipo de requisito')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_vacunas', to='travel_advisories.alerta')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_vacunas', to='travel_advisories.vacuna')),
            ],
            options={
                'verbose_name': 'Requisito de Vacuna',
                'verbose_name_plural': 'Requisitos de Vacunas',
                'ordering': ['pais', 'tipo'],
            },
        ),
    ]
