# Generated by Django 5.2.17 on 2026-09-28 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0002_alter_destino_pais'),
        ('travel_advisories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinos.destino', to_field='pais'),
        ),
    ]
