# Generated by Django 5.2.17 on 2026-09-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Viajero',
                'verbose_name_plural': 'Viajeros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('cupos', models.PositiveIntegerField(max_length=10)),
                ('estado', models.CharField(choices=[('A', 'Abierto'), ('C', 'Completo'), ('F', 'Finalizado')], default='0', max_length=1, verbose_name='Estado')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='destinos.destino')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['inicio', 'fin'],
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('O', 'Organizador'), ('V', 'Viajero'), ('I', 'Invitado')], default='V', max_length=1, verbose_name='Rol')),
                ('estado', models.CharField(choices=[('C', 'Confirmado'), ('P', 'Pendiente'), ('N', 'No viaja')], default='P', max_length=1, verbose_name='Estado')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='travelers.viaje')),
                ('viajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='travelers.viajero')),
            ],
            options={
                'verbose_name': 'Participacion',
                'verbose_name_plural': 'Participaciones',
                'ordering': ['viaje', 'viajero'],
            },
        ),
    ]
